#!/usr/bin/env python3
"""Mint activation codes for the map-license mod.

Produces two files:

  * a plaintext list of codes - the batch you hand out to buyers, and the only
    place these codes will ever exist. Keep it, back it up, never ship it.
  * codes.json - salted SHA-256 digests only, which is what goes in the jar.

Re-running against an existing codes.json keeps its salt and appends to its
digest list, so a second batch does not invalidate the first.

    python3 tools/generate_codes.py --count 200 \
        --out-codes tools/codes-batch1.txt \
        --out-hashes src/main/resources/map-license/codes.json
"""

import argparse
import base64
import hashlib
import json
import os
import secrets
import sys

# Crockford base32: no I, L, O or U, so nothing in a code can be misread as
# something else when a buyer types it off a receipt.
ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def make_code(length: int, group: int) -> str:
    body = "".join(secrets.choice(ALPHABET) for _ in range(length))
    if group <= 0:
        return body
    return "-".join(body[i:i + group] for i in range(0, len(body), group))


def normalize(code: str) -> str:
    """Must match LicenseCodes.normalize on the Java side, character for character."""
    folded = {"I": "1", "L": "1", "O": "0", "U": "V"}
    out = []
    for char in code.upper():
        char = folded.get(char, char)
        if char in ALPHABET:
            out.append(char)
    return "".join(out)


def digest(salt: bytes, code: str) -> str:
    sha = hashlib.sha256()
    sha.update(salt)
    sha.update(normalize(code).encode("utf-8"))
    return base64.b64encode(sha.digest()).decode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate activation codes for map-license.")
    parser.add_argument("--count", type=int, default=100, help="how many codes to mint")
    parser.add_argument("--length", type=int, default=16, help="characters per code (16 = 80 bits)")
    parser.add_argument("--group", type=int, default=4, help="hyphen group size, 0 for none")
    parser.add_argument("--out-codes", default="tools/codes.txt", help="plaintext list to keep private")
    parser.add_argument("--out-hashes", default="src/main/resources/map-license/codes.json",
                        help="digest list to embed in the jar")
    args = parser.parse_args()

    if args.count < 1:
        parser.error("--count must be at least 1")
    if args.length < 12:
        parser.error("--length below 12 leaves codes guessable; use 16 or more")

    salt = secrets.token_bytes(16)
    existing = []

    if os.path.exists(args.out_hashes):
        with open(args.out_hashes, encoding="utf-8") as handle:
            previous = json.load(handle)
        stored_salt = base64.b64decode(previous.get("salt", ""))
        existing = previous.get("hashes", [])
        # An all-zero salt is the placeholder shipped in the repo; anything else
        # is a real batch whose digests must stay verifiable.
        if stored_salt and any(stored_salt):
            salt = stored_salt
            print(f"Reusing salt from {args.out_hashes} ({len(existing)} code(s) already embedded)")
        else:
            existing = []

    codes = []
    seen = set()
    while len(codes) < args.count:
        code = make_code(args.length, args.group)
        if code in seen:
            continue
        seen.add(code)
        codes.append(code)

    hashes = list(dict.fromkeys(existing + [digest(salt, code) for code in codes]))

    os.makedirs(os.path.dirname(os.path.abspath(args.out_codes)), exist_ok=True)
    with open(args.out_codes, "w", encoding="utf-8") as handle:
        handle.write("\n".join(codes) + "\n")

    os.makedirs(os.path.dirname(os.path.abspath(args.out_hashes)), exist_ok=True)
    with open(args.out_hashes, "w", encoding="utf-8") as handle:
        json.dump({
            "_comment": "Salted SHA-256 digests of every code this build accepts. "
                        "Generated by tools/generate_codes.py - do not hand-edit.",
            "salt": base64.b64encode(salt).decode("ascii"),
            "hashes": hashes,
        }, handle, indent="\t")
        handle.write("\n")

    print(f"Wrote {len(codes)} new code(s) to {args.out_codes}")
    print(f"Wrote {len(hashes)} digest(s) to {args.out_hashes}")
    print("Rebuild the mod so the new digests end up in the jar.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
